/**
* iCure Cloud API Documentation
* Spring shop sample application
*
* The version of the OpenAPI document: v0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.icure.kraken.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param code 
 * @param description 
 */

data class AtcDto (
    @Json(name = "code")
    val code: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null
)

