/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.github.pozo.KotlinBuilder


/**
 * 
 *
 * @param source 
 * @param target 
 * @param filter 
 * @param localTarget 
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class DatabaseSynchronizationDto (

    @field:JsonProperty("source")
    val source: kotlin.String? = null,

    @field:JsonProperty("target")
    val target: kotlin.String? = null,

    @field:JsonProperty("filter")
    val filter: kotlin.String? = null,

    @field:JsonProperty("localTarget")
    val localTarget: DatabaseSynchronizationDto.LocalTarget? = null

) {

    /**
     * 
     *
     * Values: base,healthdata,patient
     */
    enum class LocalTarget(val value: kotlin.String) {
        @JsonProperty(value = "base") base("base"),
        @JsonProperty(value = "healthdata") healthdata("healthdata"),
        @JsonProperty(value = "patient") patient("patient");
    }
}

