/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param isSpecialist
 * @param nihii
 * @param bic
 * @param iban
 * @param bce
 * @param ssin
 * @param lastName
 * @param firstName
 * @param phoneNumber
 * @param conventionCode
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class InvoiceSender(

    @field:JsonProperty("isSpecialist")
    val isSpecialist: kotlin.Boolean = false,

    @field:JsonProperty("nihii")
    val nihii: kotlin.Long? = null,

    @field:JsonProperty("bic")
    val bic: kotlin.String? = null,

    @field:JsonProperty("iban")
    val iban: kotlin.String? = null,

    @field:JsonProperty("bce")
    val bce: kotlin.Long? = null,

    @field:JsonProperty("ssin")
    val ssin: kotlin.String? = null,

    @field:JsonProperty("lastName")
    val lastName: kotlin.String? = null,

    @field:JsonProperty("firstName")
    val firstName: kotlin.String? = null,

    @field:JsonProperty("phoneNumber")
    val phoneNumber: kotlin.Long? = null,

    @field:JsonProperty("conventionCode")
    val conventionCode: kotlin.Int? = null

)
