/**
* iCure Cloud API Documentation
* Spring shop sample application
*
* The version of the OpenAPI document: v0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.icure.kraken.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param secretForeignKeys 
 * @param exportAsPMF 
 * @param comment 
 * @param softwareName 
 * @param softwareVersion 
 */

data class SoftwareMedicalFileExportDto (
    @Json(name = "secretForeignKeys")
    val secretForeignKeys: kotlin.collections.List<kotlin.String>,
    @Json(name = "exportAsPMF")
    val exportAsPMF: kotlin.Boolean,
    @Json(name = "comment")
    val comment: kotlin.String? = null,
    @Json(name = "softwareName")
    val softwareName: kotlin.String? = null,
    @Json(name = "softwareVersion")
    val softwareVersion: kotlin.String? = null
)

