/**
 * iCure Data Stack API Documentation
 *
 * The iCure Data Stack Application API is the native interface to iCure.
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param services
 * @param healthElements
 * @param partnerships
 * @param patientHealthcareParties
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class SumehrContentDto(

    @field:JsonProperty("services")
    val services: kotlin.collections.List<ServiceDto>? = null,

    @field:JsonProperty("healthElements")
    val healthElements: kotlin.collections.List<HealthElementDto>? = null,

    @field:JsonProperty("partnerships")
    val partnerships: kotlin.collections.List<PartnershipDto>? = null,

    @field:JsonProperty("patientHealthcareParties")
    val patientHealthcareParties: kotlin.collections.List<PatientHealthCarePartyDto>? = null

)
