/**
* iCure Cloud API Documentation
* Spring shop sample application
*
* The version of the OpenAPI document: v0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.icure.kraken.client.models

import io.icure.kraken.client.models.RouteOfAdministrationDto
import io.icure.kraken.client.models.SamTextDto
import io.icure.kraken.client.models.VirtualFormDto
import io.icure.kraken.client.models.VirtualIngredientDto

import com.squareup.moshi.Json

/**
 * 
 * @param code 
 * @param virtualForm 
 * @param routeOfAdministrations 
 * @param name 
 * @param phaseNumber 
 * @param virtualIngredients 
 */

data class VmpComponentDto (
    @Json(name = "code")
    val code: kotlin.String? = null,
    @Json(name = "virtualForm")
    val virtualForm: VirtualFormDto? = null,
    @Json(name = "routeOfAdministrations")
    val routeOfAdministrations: kotlin.collections.List<RouteOfAdministrationDto>? = null,
    @Json(name = "name")
    val name: SamTextDto? = null,
    @Json(name = "phaseNumber")
    val phaseNumber: kotlin.Int? = null,
    @Json(name = "virtualIngredients")
    val virtualIngredients: kotlin.collections.List<VirtualIngredientDto>? = null
)

