/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.AmppComponentDto
import io.swagger.client.models.AtcDto
import io.swagger.client.models.CommercializationDto
import io.swagger.client.models.CompanyDto
import io.swagger.client.models.DmppDto
import io.swagger.client.models.QuantityDto
import io.swagger.client.models.SamTextDto
import io.swagger.client.models.SupplyProblemDto

/**
 * 
 * @param from 
 * @param to 
 * @param ctiExtended 
 * @param orphan 
 * @param leafletLink 
 * @param spcLink 
 * @param rmaPatientLink 
 * @param rmaProfessionalLink 
 * @param parallelCircuit 
 * @param parallelDistributor 
 * @param packMultiplier 
 * @param packAmount 
 * @param packDisplayValue 
 * @param status 
 * @param atcs 
 * @param crmLink 
 * @param deliveryModusCode 
 * @param deliveryModus 
 * @param deliveryModusSpecification 
 * @param distributorCompany 
 * @param singleUse 
 * @param speciallyRegulated 
 * @param abbreviatedName 
 * @param prescriptionName 
 * @param note 
 * @param posologyNote 
 * @param noGenericPrescriptionReasons 
 * @param exFactoryPrice 
 * @param reimbursementCode 
 * @param definedDailyDose 
 * @param officialExFactoryPrice 
 * @param realExFactoryPrice 
 * @param pricingInformationDecisionDate 
 * @param components 
 * @param commercializations 
 * @param supplyProblems 
 * @param dmpps 
 * @param vaccineIndicationCodes 
 */
data class AmppDto (
    val orphan: kotlin.Boolean,
    val atcs: kotlin.Array<AtcDto>,
    val dmpps: kotlin.Array<DmppDto>
,
    val from: kotlin.Long? = null,
    val to: kotlin.Long? = null,
    val ctiExtended: kotlin.String? = null,
    val leafletLink: SamTextDto? = null,
    val spcLink: SamTextDto? = null,
    val rmaPatientLink: SamTextDto? = null,
    val rmaProfessionalLink: SamTextDto? = null,
    val parallelCircuit: kotlin.Int? = null,
    val parallelDistributor: kotlin.String? = null,
    val packMultiplier: kotlin.Int? = null,
    val packAmount: QuantityDto? = null,
    val packDisplayValue: kotlin.String? = null,
    val status: AmppDto.Status? = null,
    val crmLink: SamTextDto? = null,
    val deliveryModusCode: kotlin.String? = null,
    val deliveryModus: SamTextDto? = null,
    val deliveryModusSpecification: SamTextDto? = null,
    val distributorCompany: CompanyDto? = null,
    val singleUse: kotlin.Boolean? = null,
    val speciallyRegulated: kotlin.Int? = null,
    val abbreviatedName: SamTextDto? = null,
    val prescriptionName: SamTextDto? = null,
    val note: SamTextDto? = null,
    val posologyNote: SamTextDto? = null,
    val noGenericPrescriptionReasons: kotlin.Array<SamTextDto>? = null,
    val exFactoryPrice: kotlin.Double? = null,
    val reimbursementCode: kotlin.Int? = null,
    val definedDailyDose: QuantityDto? = null,
    val officialExFactoryPrice: kotlin.Double? = null,
    val realExFactoryPrice: kotlin.Double? = null,
    val pricingInformationDecisionDate: kotlin.Long? = null,
    val components: kotlin.Array<AmppComponentDto>? = null,
    val commercializations: kotlin.Array<CommercializationDto>? = null,
    val supplyProblems: kotlin.Array<SupplyProblemDto>? = null,
    val vaccineIndicationCodes: kotlin.Array<kotlin.String>? = null
) {
    /**
    * 
    * Values: aUTHORIZED,sUSPENDED,rEVOKED
    */
    enum class Status(val value: kotlin.String){
        aUTHORIZED("AUTHORIZED"),
        sUSPENDED("SUSPENDED"),
        rEVOKED("REVOKED");
    }
}