/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param rev 
 * @param deletionDate 
 * @param userId 
 * @param descr 
 * @param entityType 
 * @param subType 
 * @param defaultTemplate 
 * @param entity 
 */
data class EntityTemplateDto (
    val id: kotlin.String,
    val entity: kotlin.Array<kotlin.collections.Map<kotlin.String, kotlin.Any>>
,
    val rev: kotlin.String? = null,
    val deletionDate: kotlin.Long? = null,
    val userId: kotlin.String? = null,
    val descr: kotlin.String? = null,
    val entityType: kotlin.String? = null,
    val subType: kotlin.String? = null,
    val defaultTemplate: kotlin.Boolean? = null
) {
}