/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param rev 
 * @param deletionDate 
 * @param name 
 * @param password 
 * @param servers 
 * @param superAdmin 
 * @param superGroup 
 */
data class GroupDto (
    val id: kotlin.String,
    val superAdmin: kotlin.Boolean
,
    val rev: kotlin.String? = null,
    val deletionDate: kotlin.Long? = null,
    val name: kotlin.String? = null,
    val password: kotlin.String? = null,
    val servers: kotlin.Array<kotlin.String>? = null,
    val superGroup: kotlin.String? = null
) {
}