/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param parameters 
 * @param hospitalisation 
 * @param ambulatory 
 * @param dental 
 * @param identificationNumber 
 * @param insuranceId 
 * @param startDate 
 * @param endDate 
 * @param titularyId 
 * @param encryptedSelf 
 */
data class InsurabilityDto (
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>
,
    val hospitalisation: kotlin.Boolean? = null,
    val ambulatory: kotlin.Boolean? = null,
    val dental: kotlin.Boolean? = null,
    val identificationNumber: kotlin.String? = null,
    val insuranceId: kotlin.String? = null,
    val startDate: kotlin.Long? = null,
    val endDate: kotlin.Long? = null,
    val titularyId: kotlin.String? = null,
    val encryptedSelf: kotlin.String? = null
) {
}