/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CodeStubDto
import io.swagger.client.models.DelegationDto
import io.swagger.client.models.MessageReadStatusDto

/**
 * 
 * @param id 
 * @param rev 
 * @param created 
 * @param modified 
 * @param author 
 * @param responsible 
 * @param medicalLocationId 
 * @param tags 
 * @param codes 
 * @param endOfLife 
 * @param deletionDate 
 * @param fromAddress 
 * @param fromHealthcarePartyId 
 * @param formId 
 * @param status 
 * @param recipientsType 
 * @param recipients 
 * @param toAddresses 
 * @param received 
 * @param sent 
 * @param metas 
 * @param readStatus 
 * @param transportGuid 
 * @param remark 
 * @param conversationGuid 
 * @param subject 
 * @param invoiceIds 
 * @param parentId 
 * @param externalRef 
 * @param unassignedResults 
 * @param assignedResults 
 * @param senderReferences 
 * @param secretForeignKeys 
 * @param cryptedForeignKeys 
 * @param delegations 
 * @param encryptionKeys 
 * @param encryptedSelf 
 */
data class MessageDto (
    val id: kotlin.String,
    val tags: kotlin.Array<CodeStubDto>,
    val codes: kotlin.Array<CodeStubDto>,
    val recipients: kotlin.Array<kotlin.String>,
    val toAddresses: kotlin.Array<kotlin.String>,
    val metas: kotlin.collections.Map<kotlin.String, kotlin.String>,
    val readStatus: kotlin.collections.Map<kotlin.String, MessageReadStatusDto>,
    val invoiceIds: kotlin.Array<kotlin.String>,
    val unassignedResults: kotlin.Array<kotlin.String>,
    val assignedResults: kotlin.collections.Map<kotlin.String, kotlin.String>,
    val senderReferences: kotlin.collections.Map<kotlin.String, kotlin.String>,
    val secretForeignKeys: kotlin.Array<kotlin.String>,
    val cryptedForeignKeys: kotlin.collections.Map<kotlin.String, kotlin.Array<DelegationDto>>,
    val delegations: kotlin.collections.Map<kotlin.String, kotlin.Array<DelegationDto>>,
    val encryptionKeys: kotlin.collections.Map<kotlin.String, kotlin.Array<DelegationDto>>
,
    val rev: kotlin.String? = null,
    val created: kotlin.Long? = null,
    val modified: kotlin.Long? = null,
    val author: kotlin.String? = null,
    val responsible: kotlin.String? = null,
    val medicalLocationId: kotlin.String? = null,
    val endOfLife: kotlin.Long? = null,
    val deletionDate: kotlin.Long? = null,
    val fromAddress: kotlin.String? = null,
    val fromHealthcarePartyId: kotlin.String? = null,
    val formId: kotlin.String? = null,
    val status: kotlin.Int? = null,
    val recipientsType: kotlin.String? = null,
    val received: kotlin.Long? = null,
    val sent: kotlin.Long? = null,
    val transportGuid: kotlin.String? = null,
    val remark: kotlin.String? = null,
    val conversationGuid: kotlin.String? = null,
    val subject: kotlin.String? = null,
    val parentId: kotlin.String? = null,
    val externalRef: kotlin.String? = null,
    val encryptedSelf: kotlin.String? = null
) {
}