/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param groupId 
 * @param userId 
 * @param groupName 
 */
data class UserGroupDto (

    val groupId: kotlin.String? = null,
    val userId: kotlin.String? = null,
    val groupName: kotlin.String? = null
) {
}